chore: fix blue-toggle and powermenu buttons in swaync and waybar

diff --git a/bin/canvas-2latex b/bin/canvas-2latex
--- a/bin/canvas-2latex
+++ b/bin/canvas-2latex
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck disable=SC2181
 
 IMAGE="/tmp/canvas-draw.png"
 
@@ -14,18 +15,13 @@ IMAGE="/tmp/canvas-draw.png"
 	exit 1
 }
 
-LLAVE="$(cat $XDG_CACHE_HOME/gemini_key)"
+LLAVE="$(cat "$XDG_CACHE_HOME"/gemini_key)"
 PROMPT="
 Esta es una imagen de una ecuación o expresión matemática escrita a mano. Convierte esta imagen a código LaTeX preciso y correcto.
 Responde únicamente con el código LaTeX de la ecuación sin estar rodeado por backtics:
 "
 
 IMAGE_DATA=$(base64 -w 0 "$IMAGE")
-
-if ! curl -s --head --request GET https://generativelanguage.googleapis.com; then
-	notify-send -e -i system-error "$(basename "$0")" "Error de conexión"
-	exit 1
-fi
 
 OUTPUT_JSON="/tmp/canvas2latex_output.json"
 LATEX_OUTPUT="/tmp/canvas2latex_result.txt"
@@ -35,27 +31,33 @@ curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:g
 	-H "Content-Type: application/json" \
 	-H "X-goog-api-key: $LLAVE" \
 	-X POST \
-	-d "{
-    \"contents\": [
-      {
-        \"parts\": [
-          {
-            \"text\": \"$PROMPT\"
-          },
-          {
-            \"inline_data\": {
-              \"mime_type\": \"image/png\",
-              \"data\": \"$IMAGE_DATA\"
-            }
-          }
-        ]
-      }
-    ]
-  }" 2>/dev/null >$OUTPUT_JSON
+	-d "
+	{
+	  \"contents\": [
+	    {
+	      \"parts\": [
+	        {
+	          \"text\": \"$PROMPT\"
+	        },
+	        {
+	          \"inline_data\": {
+	            \"mime_type\": \"image/png\",
+	            \"data\": \"$IMAGE_DATA\"
+	          }
+	        }
+	      ]
+	    }
+	  ]
+	}" 2>/dev/null >$OUTPUT_JSON
+
+if [ $? -ne 0 ]; then
+	notify-send -e -i system-error "$(basename "$0")" "Error de conexión"
+	exit 1
+fi
 
 # Extramos solo el código latex
 jq -r '.candidates[0].content.parts[0].text' "$OUTPUT_JSON" >"$LATEX_OUTPUT"
 
-notify-send -e -i texmaker "$(basename "$0")" "\$$(cat $LATEX_OUTPUT)\$"
+notify-send -e -i texmaker "$(basename "$0")" "Texto copiado al portapapeles"
 
 wl-copy "$(cat $LATEX_OUTPUT)"
