chore: remove useless comments chore(lf): improve text preview logic chore(nvim): switch to pylsp for python lsp chore(nix.json): add jetbrains idea package chore(canvas-*): use centralized temp directory fix(install.sh): don't update packages, not possible on old ISO fix(stage3.sh): source profile manually before it's correctly linked feat(nix-conf): delete garbage before package installation chore(nix.json): switch packages to 25.11 tag feat(shell-utils): add error print func to improve debugging fix(scripts): source shell utils using absolute path chore(update.sh): run fc-cache mid-script fix(video_drivers.json): missing comma chore(stage1.sh): remove opendoas package fix(stage3.sh): create gnupg dir before yay-install (needed for building aur pkgs) fix(stage3.sh): sudo -> doas: tee -a /etc/vconsole.conf chore(tauon-config): make script "set -e" safe fix(firefox-config): set +e fix(update.sh): remove unneeded -d flag from updater/* scripts fix(update.sh): run nix-conf in background after updater/* scripts fix(profile): source aliasrc only if it exists chore(firefox-config,tauon-config): rerun apps if needed files are missing fix(update.sh): create zsh config dir before trying to symlink zprofile chore(lf): don't hide log files by default chore(shell-utils): use echo -n for log func fix(screenshot): set +u feat(firefox-config): log unsuccessful firefox launches fix(gitignore): ignore zprofile link

diff --git a/assets/shell/shell-utils b/assets/shell/shell-utils
--- a/assets/shell/shell-utils
+++ b/assets/shell/shell-utils
@@ -1,9 +1,25 @@
-#!/bin/sh
+#!/bin/bash
+
+set -Eeuo pipefail
+
+export LOG_BASE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles"
+export TMP_BASE_DIR="/tmp/00_dotfiles"
 
 ensure_dir() {
 	[ ! -d "$1" ] && mkdir -p "$1"
 	echo "$1"
 }
+
+# Utilidad para facilitar el depurado de los scripts
+# Todos los scripts que importen el archivo deberán usar bash para poder
+# hacer uso de variables como $BASH_COMMAND
+
+error_trap() {
+	local exit_code=$?
+	log "($exit_code) [$(basename "$0")] en línea $1: $2" ERROR
+}
+
+trap 'error_trap $LINENO "$BASH_COMMAND"' ERR
 
 # Utilidades para guardar los logs en un solo directorio
 #
@@ -13,15 +29,12 @@ ensure_dir() {
 #
 # o para que la actualización de la variable LOG_DIR sea más explícita:
 #     LOG_DIR=$(initlog <directorio>)
-#
-
-LOG_BASE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles"
 
 log() {
 	MSG="$1"
 	LEVEL="${2:-ERROR}"
 	ensure_dir "${LOG_DIR:-$LOG_BASE_DIR}" >/dev/null
-	echo "$(date '+%Y-%m-%d %H:%M:%S') [$LEVEL] $MSG" |
+	echo -n "$(date '+%Y-%m-%d %H:%M:%S') [$LEVEL] $MSG" |
 		tee -a "${LOG_DIR:-$LOG_BASE_DIR}/errors.log"
 }
 
@@ -31,9 +44,6 @@ init_log() {
 }
 
 # Utilidades para guardar los archivos temporales en un solo directorio
-#
-
-TMP_BASE_DIR="/tmp/00_dotfiles"
 
 get_tmp() {
 	ensure_dir "$TMP_BASE_DIR/$1"
